
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.SQLException;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sajith
 */
public class ManageRoomsForm extends javax.swing.JFrame {
    
    ROOMS room = new ROOMS();

    /**
     * Creates new form ManageRoomsForm
     */
    public ManageRoomsForm() {
        initComponents();
        
       //display Room-Type id  in combobox 
        room.fillRoomsType_combobox(jComboBox_Type);
        
        //show all rooms in j table
        room.fillRoomsDataJTable(jTable1);
        
        //set height to jtable
        jTable1.setRowHeight(40);
        
        // create a button group for radio button
        ButtonGroup bg = new ButtonGroup();
        bg.add(jRadioButtonYes);
        bg.add(jRadioButtonNo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jTextField_RoomNo = new javax.swing.JTextField();
        jLabel_id = new javax.swing.JLabel();
        jLabel_Fname = new javax.swing.JLabel();
        jTextField_phoneNo = new javax.swing.JTextField();
        jLabel_Lname = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton_addRoom = new javax.swing.JButton();
        jButton_editRoomDetails = new javax.swing.JButton();
        jButton_removeRooms = new javax.swing.JButton();
        jButton_clear = new javax.swing.JButton();
        jButton_Refresh = new javax.swing.JButton();
        jComboBox_Type = new javax.swing.JComboBox<>();
        jButton_showRoomType = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jRadioButtonYes = new javax.swing.JRadioButton();
        jRadioButtonNo = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Manage Rooms");

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonBack)
                .addGap(242, 242, 242)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBack)
                    .addComponent(jLabel1))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel_id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_id.setText("Number :");

        jLabel_Fname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Fname.setText("Type :");

        jLabel_Lname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Lname.setText("Phone No :");

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number", "Type", "Phone Number", "Reserved"
            }
        )
        // make the jtable not editable
        {public boolean isCellEditable(int row, int column){return false;}}

    );
    jTable1.setGridColor(new java.awt.Color(255, 255, 0));
    jTable1.setSelectionBackground(new java.awt.Color(0, 204, 204));
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable1MouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(jTable1);

    jButton_addRoom.setBackground(new java.awt.Color(255, 255, 0));
    jButton_addRoom.setText("Add New Room");
    jButton_addRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButton_addRoom.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton_addRoomActionPerformed(evt);
        }
    });

    jButton_editRoomDetails.setBackground(new java.awt.Color(255, 255, 0));
    jButton_editRoomDetails.setIcon(new javax.swing.ImageIcon("C:\\Users\\sajith\\Desktop\\New folder (4)\\icons8_edit_25px.png")); // NOI18N
    jButton_editRoomDetails.setText("Edit");
    jButton_editRoomDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButton_editRoomDetails.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton_editRoomDetailsActionPerformed(evt);
        }
    });

    jButton_removeRooms.setBackground(new java.awt.Color(255, 255, 0));
    jButton_removeRooms.setText("Remove");
    jButton_removeRooms.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButton_removeRooms.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton_removeRoomsActionPerformed(evt);
        }
    });

    jButton_clear.setBackground(new java.awt.Color(255, 51, 51));
    jButton_clear.setText("Clear Fields");
    jButton_clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButton_clear.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton_clearActionPerformed(evt);
        }
    });

    jButton_Refresh.setText("Refresh");
    jButton_Refresh.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton_RefreshActionPerformed(evt);
        }
    });

    jComboBox_Type.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

    jButton_showRoomType.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    jButton_showRoomType.setText("Show Type");
    jButton_showRoomType.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton_showRoomTypeActionPerformed(evt);
        }
    });

    jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel2.setText("Reserved :");

    jRadioButtonYes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jRadioButtonYes.setText("Yes");

    jRadioButtonNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jRadioButtonNo.setText("No");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jRadioButtonYes)
            .addGap(28, 28, 28)
            .addComponent(jRadioButtonNo)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jRadioButtonYes)
                .addComponent(jRadioButtonNo))
            .addContainerGap())
    );

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(jButton_addRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton_editRoomDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton_removeRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(45, 45, 45)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel_id)
                                        .addComponent(jLabel_Fname)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_Lname, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField_RoomNo)
                                .addComponent(jTextField_phoneNo, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jComboBox_Type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton_showRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(93, 93, 93)))))
                    .addGap(0, 32, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButton_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(18, 18, 18)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButton_Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(24, 24, 24))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField_RoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_id))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel_Fname)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_Type, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_showRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField_phoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_Lname))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addComponent(jLabel2))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGap(157, 157, 157)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_removeRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_editRoomDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_addRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(26, 26, 26)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jButton_clear, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addComponent(jButton_Refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap(55, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // Display the selected row data in the jfields

        //get the jtable model
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        //get selected row index
        int rIndex = jTable1.getSelectedRow();

        //display data
        jTextField_RoomNo.setText(model.getValueAt(rIndex, 0).toString());
        jComboBox_Type.setSelectedItem(model.getValueAt(rIndex, 1).toString());
        jTextField_phoneNo.setText(model.getValueAt(rIndex, 2).toString());
        
        
       // String isReeservred = (String) model.getValueAt(rIndex,3);
        
        String isReeservred  = model.getValueAt(rIndex, 3).toString();
        
        if (isReeservred.equals("Yes") )
        {
        jRadioButtonYes.setSelected(true);
        
        }else if(isReeservred.equals("No") )
                {
                
                jRadioButtonNo.setSelected(true );
                }
        
        //String isReserved = model.getValueAt(rIndex, 3).toString());
        
        
        

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton_addRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addRoomActionPerformed
     
// add a new room
    try{
        // get data frome the fields
    int roomNumber = Integer.valueOf(jTextField_RoomNo.getText());
    int roomType;
        roomType = Integer.valueOf(jComboBox_Type.getSelectedItem().toString());
        String phone = jTextField_phoneNo.getText();
        
        if(room.addRooms(roomNumber, roomType, phone))
        {
        JOptionPane.showMessageDialog(rootPane, "New Room added succeesfully ", "Add Room", JOptionPane.INFORMATION_MESSAGE);
        
        }
        else{
                    JOptionPane.showMessageDialog(rootPane, "Not added Room", "Add Room", JOptionPane.ERROR_MESSAGE);
                }
    
    }catch(Exception ex){
        
        ex.printStackTrace();
    }      



    }//GEN-LAST:event_jButton_addRoomActionPerformed

    
    
    
    private void jButton_editRoomDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editRoomDetailsActionPerformed
        // edit a client details

        int roomNumber = 0;
      //  int roomNumber;
        int roomType;
        roomType = Integer.valueOf(jComboBox_Type.getSelectedItem().toString());
        String phone = jTextField_phoneNo.getText();
        String isReserved = "No";
        
        
        if (jRadioButtonYes.isSelected())
        {
        
        isReserved = "Yes";
        }
        
        
        
        try {
            roomNumber = Integer.valueOf(jTextField_RoomNo.getText());
            
            if (room.updaterooms(roomNumber, roomType, phone, isReserved))
            {
                JOptionPane.showMessageDialog(rootPane, "New data updated succeesfully ", "Update client", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "client data Not updated", "Update client", JOptionPane.ERROR_MESSAGE);
                
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(ManageRoomsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

       
            
           

    }//GEN-LAST:event_jButton_editRoomDetailsActionPerformed

    private void jButton_removeRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_removeRoomsActionPerformed

        int roomNumber;
        roomNumber = Integer.valueOf (jTextField_RoomNo.getText());
        
        if(room.removeRoom(roomNumber))
        {
           
            JOptionPane.showMessageDialog(rootPane, "Room data deleted succeesfully ", "Remove Room", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Room data Not deleted", "Remove Room", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton_removeRoomsActionPerformed

    private void jButton_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_clearActionPerformed
        //clear textfields

        jTextField_RoomNo.setText("");
        jTextField_phoneNo.setText("");
        jComboBox_Type.setSelectedIndex(0);
       // jRadioButtonYes.setSelected(false);
        jRadioButtonNo.setSelected(true);

    }//GEN-LAST:event_jButton_clearActionPerformed

    private void jButton_RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RefreshActionPerformed
       //clear the jlable first
        jTable1.setModel(new DefaultTableModel(null, new Object[]{"Number","Type","Phone Number","Reserved"}));

        //populate the jtable
        room.fillRoomsDataJTable(jTable1);
    }//GEN-LAST:event_jButton_RefreshActionPerformed

    private void jButton_showRoomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_showRoomTypeActionPerformed
        ALL_ROOMS_TYPE_FORM roomType = new ALL_ROOMS_TYPE_FORM();
        roomType.setVisible(true);
        roomType.pack();
        roomType.setLocationRelativeTo(null);
        roomType.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton_showRoomTypeActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
         // Display the selected row data in the jfields
        
        
        //get the jtable model
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        //get selected row index
        int rIndex = jTable1.getSelectedRow();
        
        //display data
        jTextField_RoomNo.setText(model.getValueAt(rIndex, 0).toString());
        jComboBox_Type.setSelectedItem(model.getValueAt(rIndex, 1).toString());
        jTextField_phoneNo.setText(model.getValueAt(rIndex, 2).toString());
       
        
        String isReserved = model.getValueAt(rIndex, 3).toString();
        
        if (isReserved.equals("Yes"))
        {
        
        jRadioButtonYes.setSelected(true);
        }
        else if(isReserved.equals("No"))
        {
        jRadioButtonYes.setSelected(false);
        }
        
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
       Mainform M = new Mainform();
                    M.setVisible(true);
                    M.pack();
                    M.setLocationRelativeTo(null);
                    this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageRoomsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageRoomsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageRoomsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageRoomsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageRoomsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButton_Refresh;
    private javax.swing.JButton jButton_addRoom;
    private javax.swing.JButton jButton_clear;
    private javax.swing.JButton jButton_editRoomDetails;
    private javax.swing.JButton jButton_removeRooms;
    private javax.swing.JButton jButton_showRoomType;
    private javax.swing.JComboBox<String> jComboBox_Type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Fname;
    private javax.swing.JLabel jLabel_Lname;
    private javax.swing.JLabel jLabel_id;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonNo;
    private javax.swing.JRadioButton jRadioButtonYes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_RoomNo;
    private javax.swing.JTextField jTextField_phoneNo;
    // End of variables declaration//GEN-END:variables
}
